//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mystrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mystrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HospitalProject.Mystrings", typeof(Mystrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields is empty!.
        /// </summary>
        internal static string AmCatchBox {
            get {
                return ResourceManager.GetString("AmCatchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you Sure to delete this record?.
        /// </summary>
        internal static string AmDeleteMessage {
            get {
                return ResourceManager.GetString("AmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter  Diagnosis!.
        /// </summary>
        internal static string AmDiagnosisValid {
            get {
                return ResourceManager.GetString("AmDiagnosisValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Medicines!.
        /// </summary>
        internal static string AmMedicineValid {
            get {
                return ResourceManager.GetString("AmMedicineValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Symptoms !.
        /// </summary>
        internal static string AmSymptomValid {
            get {
                return ResourceManager.GetString("AmSymptomValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved.
        /// </summary>
        internal static string AmTryMessageBox {
            get {
                return ResourceManager.GetString("AmTryMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ward type!!.
        /// </summary>
        internal static string AmWardTypeValid {
            get {
                return ResourceManager.GetString("AmWardTypeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ward !.
        /// </summary>
        internal static string AmWardValid {
            get {
                return ResourceManager.GetString("AmWardValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address!.
        /// </summary>
        internal static string ApAddressValid {
            get {
                return ResourceManager.GetString("ApAddressValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter  Age!.
        /// </summary>
        internal static string ApAgeValid {
            get {
                return ResourceManager.GetString("ApAgeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Blood group!.
        /// </summary>
        internal static string ApBloodGroup {
            get {
                return ResourceManager.GetString("ApBloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Format!! Try Again.
        /// </summary>
        internal static string ApCtachMessageBox {
            get {
                return ResourceManager.GetString("ApCtachMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter  Gender!.
        /// </summary>
        internal static string ApGenderValid {
            get {
                return ResourceManager.GetString("ApGenderValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name!.
        /// </summary>
        internal static string ApNameValid {
            get {
                return ResourceManager.GetString("ApNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is saved.
        /// </summary>
        internal static string ApTryMessageBox {
            get {
                return ResourceManager.GetString("ApTryMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Mismatched.
        /// </summary>
        internal static string Confirm_Password_Validation {
            get {
                return ResourceManager.GetString("Confirm Password Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Email.
        /// </summary>
        internal static string Email__Validation {
            get {
                return ResourceManager.GetString("Email  Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Email.
        /// </summary>
        internal static string EmailLogin {
            get {
                return ResourceManager.GetString("EmailLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \A(?:[a-z0-9!#$%&amp;&apos;*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&amp;&apos;*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z.
        /// </summary>
        internal static string Emailpattern {
            get {
                return ResourceManager.GetString("Emailpattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to the database:.
        /// </summary>
        internal static string LoginCatchMessage {
            get {
                return ResourceManager.GetString("LoginCatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string LoginSecCatchMessage {
            get {
                return ResourceManager.GetString("LoginSecCatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inavlid Username &amp; Password.
        /// </summary>
        internal static string LoginTRyelseMessage {
            get {
                return ResourceManager.GetString("LoginTRyelseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Sucessfully.
        /// </summary>
        internal static string LoginTRyifMessage {
            get {
                return ResourceManager.GetString("LoginTRyifMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter strong password.
        /// </summary>
        internal static string Password_Validation {
            get {
                return ResourceManager.GetString("Password Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password.
        /// </summary>
        internal static string PasswordLogin {
            get {
                return ResourceManager.GetString("PasswordLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$.
        /// </summary>
        internal static string Passwordpattern {
            get {
                return ResourceManager.GetString("Passwordpattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill username.
        /// </summary>
        internal static string Username_Validation {
            get {
                return ResourceManager.GetString("Username Validation", resourceCulture);
            }
        }
    }
}
